spring.application.name=smartdocs

spring.cloud.azure.cosmos.endpoint=${COSMOS_URI}
spring.cloud.azure.cosmos.key=${COSMOS_KEY}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE:smartdocs}

spring.cloud.azure.storage.blob.endpoint=${BLOB_ENDPOINT}
spring.cloud.azure.storage.blob.account-name=${BLOB_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.account-key=${BLOB_ACCOUNT_KEY}

smartdocs.storage.container-name=${BLOB_CONTAINER_NAME:documents}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
