spring.application.name=smartdocs

spring.cloud.azure.cosmos.endpoint=${COSMOS_URI}
spring.cloud.azure.cosmos.key=${COSMOS_KEY}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE:smartdocs}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
